#!/bin/sh 

LOGFILE="/tmp/updatetools.$(date +'%Y%m%d.%H.%m.%s').log"

echo "Update Script Started: $(date +'%Y-%m-%d %H:%m:%s')" >${LOGFILE}

# Update Repos
sudo apt update >>${LOGFILE}
sudo apt -y upgrade >>${LOGFILE}
sudo apt -y dist-upgrade >>${LOGFILE}
sudo apt -y autoremove >>${LOGFILE}

# Update Github Repos
cd /opt
find . -name .git -type d | xargs -n1 -P4 -I% git --git-dir=% --work-tree=%/.. pull -p >>${LOGFILE} 

# Update pip
sudo pip install pip --upgrade

# Update Steampipe
sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)" >>${LOGFILE}
steampipe plugin update --all >>${LOGFILE} 

cd /opt/steampipe-mod-aws-well-architected
steampipe mod install

cd /opt/steampipe-mod-aws-top-10
steampipe mod install

# Temporary Fix for scoutsuit blowout at build
cd /opt/ScoutSuite
virtualenv -p python3 venv && venv/bin/pip install --no-cache-dir --upgrade pip && venv/bin/pip install --no-cache-dir -r requirements.txt

# Update Go 
cd /opt/update-golang
# [[ "$(/usr/local/go/bin/go version | awk '{ print $3 }')" != "$(curl https://go.dev/VERSION?m=text)" ]] && sudo /opt/update-golang/update-golang.sh >>${LOGFILE}
sudo ./update-golang.sh >>${LOGFILE}

# updating trufflehog
cd /opt/trufflehog
sudo bash -c ". /etc/profile.d/golang_path.sh && go build -v -a -ldflags '-w -s -extldflags "-static"' -o /usr/bin/trufflehog"

# updating kubeaudit
cd /opt/kubeaudit
sudo bash -c ". /etc/profile.d/golang_path.sh && go build -v -a -ldflags '-w -s -extldflags "-static"' -o /usr/bin/kubeaudit ./cmd/ && chmod +x /usr/bin/kubeaudit"

# updating AzureHound
cd /opt/AzureHound
sudo bash -c ". /etc/profile.d/golang_path.sh && go build -v -a -ldflags '-w -s -extldflags "-static"' -o /usr/bin/AzureHound"

# fix perms
sudo chown container:container -Rv /opt/* >>${LOGFILE}

echo "Update Script Ended: $(date +'%Y-%m-%d %H:%m:%s')" >>${LOGFILE}

# stop container exiting
sleep 48h
