#!/bin/sh
echo "Update Script Started: $(date +'%Y-%m-%d %H:%m:%s')" >/tmp/updatetools.log

# Update Repos
sudo apt update >>/tmp/updatetools.log
sudo apt -y upgrade >>/tmp/updatetools.log
sudo apt -y dist-upgrade >>/tmp/updatetools.log
sudo apt -y autoremove >>/tmp/updatetools.log

# Update Github Repos
cd /opt
find . -type d -depth 1 -exec git --git-dir={}/.git --work-tree=$PWD/{} pull origin master \; >>/tmp/updatetools.log

# Update Steampipe
sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)" >>/tmp/updatetools.log
sudo steampipe plugin update --all >>/tmp/updatetools.log
echo "Update Script Ended: $(date +'%Y-%m-%d %H:%m:%s')" >>/tmp/updatetools.log

# stop container exiting
sleep infinity
