name: Create SBOM for Container image and upload vauln results to Github security

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]  
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-sbom:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (SPDX)
        run: |
          syft ghcr.io/sethbodine/audit-tools:latest -o spdx-json > sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: audit-tools-sbom
          path: sbom.spdx.json

  grype-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: generate-sbom
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      security-events: write 
      actions: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download SBOM artifact
        uses: actions/download-artifact@v5
        with:
          name: audit-tools-sbom
          path: .

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Grype (SARIF output)
        run: |
          grype sbom:sbom.spdx.json -o sarif > grype-results.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-results.sarif
