name: Grype Vulnerability Scan

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]  
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  grype-scan:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom
          path: ./sbom

      - name: Scan SBOM with Grype
        run: |
          grype sbom:./sbom/sbom.spdx.json -o table --fail-on medium

      # - name: Upload Grype scan results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: grype-scan-results
      #     path: grype-report.txt

      - name: Scan SBOM with Grype (SARIF output)
        run: |
          grype sbom:./sbom/sbom.spdx.json -o sarif > grype-report.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-report.sarif
