name: Grype Vulnerability Scan

on:
  workflow_run:
    workflows: ["Create SBOM for Container image"]  
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  grype-scan:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: audit-tools-sbom

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan SBOM with Grype (SARIF output)
        run: |
          grype sbom:sbom.spdx.json -o sarif > grype-results.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: grype-results.sarif
