name: Create SBOM for Container image

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]  
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-sbom:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (SPDX)
        run: |
          syft ghcr.io/sethbodine/audit-tools:latest -o spdx-json > sbom.spdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: audit-tools-sbom
          path: sbom.spdx.json
